export const ADD_FRIEND = 'ADD_FRIEND';
export const STAR_FRIEND = 'STAR_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';

export const REFRESH_PAGINATION = 'REFRESH_PAGINATION';
export const CHANGE_PAGINATION_PAGE = 'CHANGE_PAGINATION_PAGE';